{% set name = "gitpython" %}
{% set version = "3.1.40" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/GitPython-{{ version }}.tar.gz
  sha256: 22b126e9ffb671fdd0c129796343a02bf67bf2994b35449ffc9321aa755e18a4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - gitdb >=4.0.1,<5
    - typing_extensions >=3.7.4.3

test:
  requires:
    - git
    - pip
  imports:
    - git
    - git.index
    - git.objects
    - git.objects.submodule
    - git.refs
    - git.repo
  commands:
    - pip check

about:
  home: https://github.com/gitpython-developers/GitPython
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python Git Library
  doc_url: http://gitpython.readthedocs.org

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
    - xhochy
