travis:
  secure:
    BINSTAR_TOKEN: Kkxe3TZ2l6O5q9RumIroG+PkZNlkkAjHXJk8Mg7i1FFvi/V0/nsTJnDy91fu7w2N/25meEjhJ+MOgJ5EWOjqGMZM/3NjUwLbvNSie8BAnzKdz2hsD0LMnYgkdeVmyVlROyIl5nV0iaaFoDlmvnjjQWf5O4M38Pb47hwBuHInhtYyA5n70oGxVJ416BiO7Fwb5Wc/FOpmEBfpasmzhdar/QvqfO8C61rGtIz1NCHp5CpIIxwFw25PouYbeEu65UcnE4mLnIQg2w4C3fy5z0A5hJhAW1gGmeEoOG2+YdMyVZd4G6K1HjzlwJISAJWCfWzSsgbJOypf7E5OE5TlluilESx5BvmEyOgAKBukNgtRl6s3KKW0iU/H15UBTAtKSTkude1gFU79leBE8tfGkwmgs1widr2jvNJaoEHtJ7bQrpDNjb2C6h3x26YKprjqg5EvBjLXJC7OXwe6W7uyQQYN0/QrJht1Qy+UKTacJpntwz0+LTrR1Vt3IbpcL2DTWmefrlfIIH4KF+eo+0c+n6JeJWLp2RNRyFl49rD4Tehbb2qgbmyXD9KxvtZ+PU1r2ZBpFC/RE/7O3IQLVy9RGHVnQcSRLftVXTYQTe4CiRw08JLg0Wx4z5LD7m1NWQ2Ag2zXWznbK0cqu8P83ggNmacKzVL3KLnh6sZlYngo6dRRKJk=
appveyor:
  secure:
    BINSTAR_TOKEN: KDvUkPrcdKmV2MxakkyQlrLA0rE/6WSuXxD42UezzZjCB0TRqnnOeebSW03/SnFP
conda_forge_output_validation: true
